name: Cancel
on:
  push:
    branches:
      - master
      - next
  pull_request:
    branches:
      - master
      - next

permissions: {}

jobs:
  cancel:
    permissions:
      actions: write #  to cancel/stop running workflows (styfle/cancel-workflow-action)

    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.10.0
        with:
          workflow_id: nodejs.yml
          access_token: ${{ github.token }}
